services:
  server-neptis:
    image: "server-neptis"
    build:
      context: ./server/.
      dockerfile: Dockerfile
    container_name: server-neptis
    ports:
      - 1234:1234
    depends_on:
      - db

  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: jgrajber
    volumes:
      - ./db-init-scripts:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5050:80